Clear ProxyPool cache on discard
New functionality was introduced in Rails 5.2 to ensure forked children don't
send quit/shutdown/goodbye messages to the server on connections that belonged
to their parent. See rails/rails#31173 for more information.

We need to ensure that when the following line is called we also discard the
pools we've cached.

ActiveRecord::ConnectionAdapters:::ConnectionHandler.discard_unowned_pools

Without this change, applications using this gem and Rails 5.2.3 will run into
`NoMethodError (undefined method 'any?' for nil:NilClass)` exceptions from
forked processes (e.g. Puma/Unicorn workers) since they'll be using the cached
and discarded connection.

The upshot of this change is we can do away with code like this:
https://github.com/rails/rails/blob/c39ed435eb578c79867552c66da7eeb035fa58ad/railties/lib/rails/generators/rails/app/templates/config/puma.rb.tt#L35-L53